### ISSUE TITLE
Auto-kick Timer Doesn't Work

### ISSUE THREAD

**Issue by Willard21** [Ratismal/UNO#10] opened 2018-10-15 20:24 UTC
## Checklist

- [x] I have checked previous issues for duplicates
- [x] This issue is not related to selfhosting
- [ ] This issue is a feature request (leave unchecked for bug report)

## Expected Behavior

The game should be deleted if it doesn't start within a few minutes, and it should kick players that don't take their turn within a certain time (including the host).

## Current Behavior

Players can start a game and never end it, or even leave the server, and the channel can never again play Uno.

## Steps to Reproduce (for bugs)

1. Start game
2. Do nothing

## Context

This has been causing problems on the Discord Dungeons server (currently Spookord Dungeons for October). Multiple uno channels have been deleted or locked because of it. I know there's code in the bot to handle this situation, but it never runs.

**Comment by schrmh** [comment] 2018-10-16 09:41
If you clone the code from GitHub it and run it a game ends after one minute per default.
The public bot differs from that.

**Comment by schrmh** [comment] 2018-10-16 09:43
If you clone the code from GitHub and run it a game will end after one minute per default in case that no one joins.
The public bot differs from that.

**Comment by Willard21** [comment] 2018-10-17 16:13
Well the problem has existed for a few months now. Has it not been updated in that long? Selfhosting doesn't sound like a very appealing solution.

**Comment by Ratismal** [comment] 2018-10-17 17:47
Isolated the issue. It was caused by the bot trying to send a "your game has timed out message" to a channel that it no longer had access to, causing the rest of the game timeouts to never be called. This should be fixed now.

**Closed by Ratismal** 2018-10-17 17:47 UTC
